### ISSUE TITLE
Phantom Tap Recording

### ISSUE THREAD

**Issue by abbylindsay** [biosensics/TapRecorder#1]
Create a Mason group with a build that will keep the display on and track the amount of phantom taps and their locations. Also, have UI that shows the location of the last touch with a timestamp.

Greg is trying to get tablets from Mason (so we arent charged) to use for testing

**Comment by MarcDerhammer** [comment]
Confirmed Julia's tablet (`6665`) is recording "phantom taps"

**Comment by abbylindsay** [comment]
Done - if more work needed, then a new issue will be open
